# See https://pre-commit.ci/ for more information about pre-commit.ci
ci:
    autofix_commit_msg: "style: pre-commit fixes"
    autoupdate_schedule: quarterly
    autoupdate_commit_msg: 'chore(deps): update pre-commit hooks'
    skip:
    -   pip-compile

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.2
    hooks:
    -   id: ruff-check
    -   id: ruff-format
-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
    -   id: actionlint
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.2
    hooks:
    -   id: pip-compile
        files: |
          (?x)^(
            pyproject.toml|
            requirements/docs.requirements.txt
          )$
        args:
        -   pyproject.toml
        -   "--group=docs"
        -   "--python-version=3.14"
        -   "--output-file=requirements/docs.requirements.txt"
-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.1
    hooks:
    -   id: check-github-workflows
    -   id: check-renovate
-   repo: https://github.com/adamtheturtle/doccmd-pre-commit
    rev: v2026.1.28
    hooks:
    -   id: doccmd
        name: Ruff format docs
        language: python
        alias: ruff-format-docs
        args: ["--language", "python", "--no-pad-file", "--no-pad-groups", "--command", "ruff format", "docs/"]
        additional_dependencies:
        - ruff==0.15.2
    -   id: doccmd
        name: Ruff check fix docs
        language: python
        alias: ruff-check-fix-docs
        args: ["--language", "python", "--no-pad-file", "--no-pad-groups", "--command", "ruff check --fix", "docs/"]
        additional_dependencies:
        - ruff==0.15.2
