# See https://pre-commit.ci/ for more information about pre-commit.ci
ci:
    autoupdate_schedule: quarterly

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.9
    hooks:
    -   id: ruff-check
    -   id: ruff-format
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.17
    hooks:
    -   id: uv-lock
-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.35.0
    hooks:
    -   id: check-github-workflows
    -   id: check-renovate
-   repo: https://github.com/adamtheturtle/doccmd-pre-commit
    rev: v2025.12.10
    hooks:
    -   id: doccmd
        name: Ruff format docs
        alias: ruff-format-docs
        args: ["--language", "python", "--no-pad-file", "--no-pad-groups", "--command", "ruff format", "docs/"]
        additional_dependencies:
        - ruff==0.14.8
    -   id: doccmd
        name: Ruff check fix docs
        alias: ruff-check-fix-docs
        args: ["--language", "python", "--no-pad-file", "--no-pad-groups", "--command", "ruff check --fix", "docs/"]
        additional_dependencies:
        - ruff==0.14.8
